run/poetry/forms/__init__.py
from .poem_forms import PoemChangeMeterForm, PoemSetDefaultMeterForm
from .meter_forms import MeterUpdateForm, MeterAddForm, MeterDeleteForm
from .poet_forms import PoetUpdateForm, PoetAddForm, PoetDeleteForm


__all__ = [
    "PoemChangeMeterForm",
    "PoemSetDefaultMeterForm",
    "MeterUpdateForm",
    "MeterAddForm",
    "MeterDeleteForm",
    "PoetUpdateForm",
    "PoetAddForm",
    "PoetDeleteForm",
]

run/poetry/forms/poem_forms.py
"""Define the forms for the poetry blueprint."""

from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, BooleanField


class PoemChangeMeterForm(FlaskForm):
    """Allow user to choose the meter to scan the poem."""
    pattern = SelectField('Switch to')
    submit = SubmitField('Refresh')


class PoemSetDefaultMeterForm(PoemChangeMeterForm):
    """Allow user to set the default meter for the poem."""
    set_as_default = BooleanField('Set as the default meter')

run/poetry/__init__.py
"""Initialize the poetry blueprint."""

from flask import Blueprint

poetry = Blueprint('poetry', __name__)

from . import views

run/poetry/views/__init__.py
from .sample_views import add_samples
from .poem_views import poem_list, poem
from .meter_views import meter_list, meter
from .poet_views import poet_list, poet


__all__ = [
    "add_samples",
    "poem_list",
    "poem",
    "meter_list",
    "meter",
    "poet_list",
    "poet",
]

run/poetry/views/meter_views.py
"""Route definitions for the poetry blueprint."""

from flask import render_template, redirect, url_for
from flask_login import current_user
from run import db
from .. import poetry
from ...models import Meter, Poem, Permission
from ..forms import (
    MeterUpdateForm,
    MeterAddForm,
    MeterDeleteForm,
)


@poetry.route("/meter")
def meter_list():
    if "meters" not in db.engine.table_names():
        meters = []
    else:
        meters = Meter.query.order_by('name').all()
    return render_template("poetry/meter_list.html", meters=meters)


@poetry.route("/meter/<keyword>", methods=['GET', 'POST'])
def meter(keyword):
    """Define the meter route."""
    # if the meters table does not exist, 404 the route
    if "meters" not in db.engine.table_names():
        return render_template('main/404.html'), 404

    if keyword == 'new':
        meter = None
        poems = []
        form = MeterAddForm()
        delete_form = None

        if form.validate_on_submit():
            if current_user.can(Permission.ADD_METER):
                meter = Meter(
                    name=form.name.data,
                    pattern=form.pattern.data,
                )
                db.session.add(meter)
                db.session.commit()
                keyword = Meter.query.filter_by(
                    pattern=form.pattern.data
                ).first().id
                return redirect(url_for('poetry.meter', keyword=keyword))
    else:
        # retrieve the requested meter if it exists
        meter = Meter.query.get_or_404(keyword)

        # retrieve the poems which use this meter, if any
        poems = Poem.query.filter_by(meter=meter).all()
        if poems is None:
            poems = []

        if current_user.can(Permission.ADD_METER):
            form = MeterUpdateForm()
            form.id.data = keyword
            if form.validate_on_submit():
                meter.name = form.name.data
                meter.pattern = form.pattern.data
                db.session.commit()
                return redirect(url_for('poetry.meter', keyword=keyword))
            form.name.data = meter.name
            form.pattern.data = meter.pattern
        else:
            form = None

        if current_user.can(Permission.ADD_METER) and poems == []:
            delete_form = MeterDeleteForm()
            delete_form.id.data = keyword
            if delete_form.validate_on_submit():
                db.session.delete(meter)
                db.session.commit()
                return redirect(url_for('poetry.meter_list'))
            form.name.data = meter.name
        else:
            delete_form = None

    return render_template(
        "poetry/meter.html",
        form=form,
        delete_form=delete_form,
        meter=meter,
        poems=poems,
    )

run/poetry/views/meters.py
"""Route definitions for the poetry blueprint."""

from flask import render_template, redirect, url_for
from flask_login import current_user
from run import db
from .. import poetry
from ...models import Meter, Poem, Permission
from ..forms import (
    MeterUpdateForm,
    MeterAddForm,
    MeterDeleteForm,
)


@poetry.route("/meter")
def meter_list():
    if "meters" not in db.engine.table_names():
        meters = []
    else:
        meters = Meter.query.order_by('name').all()
    return render_template("poetry/meter_list.html", meters=meters)


@poetry.route("/meter/<keyword>", methods=['GET', 'POST'])
def meter(keyword):
    """Define the meter route."""
    # if the meters table does not exist, 404 the route
    if "meters" not in db.engine.table_names():
        return render_template('main/404.html'), 404

    if keyword == 'new':
        meter = None
        poems = []
        form = MeterAddForm()
        delete_form = None

        if form.validate_on_submit():
            if current_user.can(Permission.ADD_METER):
                meter = Meter(
                    name=form.name.data,
                    pattern=form.pattern.data,
                )
                db.session.add(meter)
                db.session.commit()
                keyword = Meter.query.filter_by(
                    pattern=form.pattern.data
                ).first().id
                return redirect(url_for('poetry.meter', keyword=keyword))
    else:
        # retrieve the requested meter if it exists
        meter = Meter.query.get_or_404(keyword)

        # retrieve the poems which use this meter, if any
        poems = Poem.query.filter_by(meter=meter).all()
        if poems is None:
            poems = []

        if current_user.can(Permission.ADD_METER):
            form = MeterUpdateForm()
            form.id.data = keyword
            if form.validate_on_submit():
                meter.name = form.name.data
                meter.pattern = form.pattern.data
                db.session.commit()
                return redirect(url_for('poetry.meter', keyword=keyword))
            form.name.data = meter.name
            form.pattern.data = meter.pattern
        else:
            form = None

        if current_user.can(Permission.ADD_METER) and poems == []:
            delete_form = MeterDeleteForm()
            delete_form.id.data = keyword
            if delete_form.validate_on_submit():
                db.session.delete(meter)
                db.session.commit()
                return redirect(url_for('poetry.meter_list'))
            form.name.data = meter.name
        else:
            delete_form = None

    return render_template(
        "poetry/meter.html",
        form=form,
        delete_form=delete_form,
        meter=meter,
        poems=poems,
    )

run/poetry/views/poem_views.py
"""Route definitions for the poetry blueprint."""

from flask import render_template, redirect, url_for
from flask_login import current_user
from run import db
from .. import poetry
from ...models import Meter, Poem, Permission
from ..helpers import stanzas
from ..forms import (
    PoemChangeMeterForm,
    PoemSetDefaultMeterForm,
)


@poetry.route("/poem")
def poem_list():
    if "poems" not in db.engine.table_names():
        poems = []
    else:
        poems = Poem.query.order_by('title').all()
    return render_template("poetry/poem_list.html", poems=poems)


@poetry.route("/poem/<keyword>", methods=['GET', 'POST'])
def poem(keyword):
    """Define the poem route."""
    # if the poems table does not exist, 404 the route
    if "poems" not in db.engine.table_names():
        return render_template('main/404.html'), 404

    # retrieve the requested poem if it exists
    poem = Poem.query.filter_by(keyword=keyword).first_or_404()

    if current_user.can(Permission.CHANGE_METER):
        form = PoemSetDefaultMeterForm()
    else:
        form = PoemChangeMeterForm()

    meters = Meter.query.order_by('name').all()
    # move the poem's default meter to the top of the drop-down
    meters.insert(0, meters.pop(meters.index(poem.meter)))
    form.pattern.choices = [(m.pattern, m.name) for m in meters]
    default_pattern, default_name = form.pattern.choices[0]
    form.pattern.choices[0] = (default_pattern, default_name + ' (default)')

    if form.validate_on_submit():
        meter = Meter.query.filter_by(pattern=form.pattern.data).first()
        if (current_user.can(Permission.CHANGE_METER)
                and form.set_as_default.data is True):
            poem.meter = meter
            db.session.commit()
            form.set_as_default.data = False
            return redirect(url_for('poetry.poem', keyword=keyword))
    else:
        meter = poem.meter

    return render_template(
        "poetry/poem.html",
        form=form,
        title=poem.title,
        poet=poem.author,
        meter=meter,
        stanzas=stanzas(poem.raw_text, meter.pattern),
    )

run/poetry/views/poems.py
"""Route definitions for the poetry blueprint."""

from flask import render_template, redirect, url_for
from flask_login import current_user
from run import db
from .. import poetry
from ...models import Meter, Poem, Permission
from ..helpers import stanzas
from ..forms import (
    PoemChangeMeterForm,
    PoemSetDefaultMeterForm,
)


@poetry.route("/poem")
def poem_list():
    if "poems" not in db.engine.table_names():
        poems = []
    else:
        poems = Poem.query.order_by('title').all()
    return render_template("poetry/poem_list.html", poems=poems)


@poetry.route("/poem/<keyword>", methods=['GET', 'POST'])
def poem(keyword):
    """Define the poem route."""
    # if the poems table does not exist, 404 the route
    if "poems" not in db.engine.table_names():
        return render_template('main/404.html'), 404

    # retrieve the requested poem if it exists
    poem = Poem.query.filter_by(keyword=keyword).first_or_404()

    if current_user.can(Permission.CHANGE_METER):
        form = PoemSetDefaultMeterForm()
    else:
        form = PoemChangeMeterForm()

    meters = Meter.query.order_by('name').all()
    # move the poem's default meter to the top of the drop-down
    meters.insert(0, meters.pop(meters.index(poem.meter)))
    form.pattern.choices = [(m.pattern, m.name) for m in meters]
    default_pattern, default_name = form.pattern.choices[0]
    form.pattern.choices[0] = (default_pattern, default_name + ' (default)')

    if form.validate_on_submit():
        meter = Meter.query.filter_by(pattern=form.pattern.data).first()
        if (current_user.can(Permission.CHANGE_METER)
                and form.set_as_default.data is True):
            poem.meter = meter
            db.session.commit()
            form.set_as_default.data = False
            return redirect(url_for('poetry.poem', keyword=keyword))
    else:
        meter = poem.meter

    return render_template(
        "poetry/poem.html",
        form=form,
        title=poem.title,
        poet=poem.author,
        meter=meter,
        stanzas=stanzas(poem.raw_text, meter.pattern),
    )

run/poetry/views/poet_views.py
"""Route definitions for the poetry blueprint."""

from flask import render_template, redirect, url_for
from flask_login import current_user
from run import db
from .. import poetry
from ...models import Poet, Poem, Permission
from ..forms import (
    PoetUpdateForm,
    PoetAddForm,
    PoetDeleteForm,
)


@poetry.route("/poet")
def poet_list():
    if "poets" not in db.engine.table_names():
        poets = []
    else:
        poets = Poet.query.order_by('name').all()
    return render_template("poetry/poet_list.html", poets=poets)


@poetry.route("/poet/<keyword>", methods=['GET', 'POST'])
def poet(keyword):
    """Define the poet route."""
    # if the poet table does not exist, 404 the route
    if "poets" not in db.engine.table_names():
        return render_template('main/404.html'), 404

    if keyword == 'new':
        poet = None
        poems = []
        form = PoetAddForm()
        delete_form = None

        if form.validate_on_submit():
            if current_user.can(Permission.ADD_POEM):
                poet = Poet(
                    name=form.name.data,
                )
                db.session.add(poet)
                db.session.commit()
                keyword = poet.query.filter_by(
                    name=form.name.data
                ).first().id
                return redirect(url_for('poetry.poet', keyword=keyword))
    else:
        # retrieve the requested poet if they exist
        poet = Poet.query.get_or_404(keyword)

        # retrieve the poems written by this poet, if any
        poems = Poem.query.filter_by(author=poet).all()
        if poems is None:
            poems = []

        if current_user.can(Permission.ADD_POEM):
            form = PoetUpdateForm()
            form.id.data = keyword
            if form.validate_on_submit():
                poet.name = form.name.data
                db.session.commit()
                return redirect(url_for('poetry.poet', keyword=keyword))
            form.name.data = poet.name
        else:
            form = None

        if current_user.can(Permission.ADD_POEM) and poems == []:
            delete_form = PoetDeleteForm()
            delete_form.id.data = keyword
            if delete_form.validate_on_submit():
                db.session.delete(poet)
                db.session.commit()
                return redirect(url_for('poetry.poet_list'))
            form.name.data = poet.name
        else:
            delete_form = None

    return render_template(
        "poetry/poet.html",
        form=form,
        delete_form=delete_form,
        poet=poet,
        poems=poems,
    )

run/poetry/views/poets.py
"""Route definitions for the poetry blueprint."""

from flask import render_template, redirect, url_for
from flask_login import current_user
from run import db
from .. import poetry
from ...models import Poet, Poem, Permission
from ..forms import (
    PoetUpdateForm,
    PoetAddForm,
    PoetDeleteForm,
)


@poetry.route("/poet")
def poet_list():
    if "poets" not in db.engine.table_names():
        poets = []
    else:
        poets = Poet.query.order_by('name').all()
    return render_template("poetry/poet_list.html", poets=poets)


@poetry.route("/poet/<keyword>", methods=['GET', 'POST'])
def poet(keyword):
    """Define the poet route."""
    # if the poet table does not exist, 404 the route
    if "poets" not in db.engine.table_names():
        return render_template('main/404.html'), 404

    if keyword == 'new':
        poet = None
        poems = []
        form = PoetAddForm()
        delete_form = None

        if form.validate_on_submit():
            if current_user.can(Permission.ADD_POEM):
                poet = Poet(
                    name=form.name.data,
                )
                db.session.add(poet)
                db.session.commit()
                keyword = poet.query.filter_by(
                    name=form.name.data
                ).first().id
                return redirect(url_for('poetry.poet', keyword=keyword))
    else:
        # retrieve the requested poet if they exist
        poet = Poet.query.get_or_404(keyword)

        # retrieve the poems written by this poet, if any
        poems = Poem.query.filter_by(author=poet).all()
        if poems is None:
            poems = []

        if current_user.can(Permission.ADD_POEM):
            form = PoetUpdateForm()
            form.id.data = keyword
            if form.validate_on_submit():
                poet.name = form.name.data
                db.session.commit()
                return redirect(url_for('poetry.poet', keyword=keyword))
            form.name.data = poet.name
        else:
            form = None

        if current_user.can(Permission.ADD_POEM) and poems == []:
            delete_form = PoetDeleteForm()
            delete_form.id.data = keyword
            if delete_form.validate_on_submit():
                db.session.delete(poet)
                db.session.commit()
                return redirect(url_for('poetry.poet_list'))
            form.name.data = poet.name
        else:
            delete_form = None

    return render_template(
        "poetry/poet.html",
        form=form,
        delete_form=delete_form,
        poet=poet,
        poems=poems,
    )

run/poetry/views/sample_views.py
"""Route definitions for the poetry blueprint."""

from flask import render_template, redirect, url_for
from .. import poetry
from ...models import Meter, Poet, Poem


@poetry.route("/add_samples")
def add_samples():
    """Define the add_samples route."""
    try:
        Meter.insert_samples()
        Poet.insert_samples()
        Poem.insert_samples()
    except Exception:
        return render_template('main/404.html'), 404
    return redirect(url_for('main.home'))

run/poetry/views/samples.py
"""Route definitions for the poetry blueprint."""

from flask import render_template, redirect, url_for
from .. import poetry
from ...models import Meter, Poet, Poem


@poetry.route("/add_samples")
def add_samples():
    """Define the add_samples route."""
    try:
        Meter.insert_samples()
        Poet.insert_samples()
        Poem.insert_samples()
    except Exception:
        return render_template('main/404.html'), 404
    return redirect(url_for('main.home'))

run/templates/poetry/meter.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
{{ title }} - Metroscope
{% endblock title %}

{% block page_content %}
<a href="{{ url_for('poetry.meter_list') }}">
    <span class="glyphicon glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    Available Meters
</a>
{% if meter is not none %}
    <h1>{{ meter.name }}</h1>
    <br>
    <p>
    {%- for beat in meter.pattern -%}
        {%- if beat == '1' -%}
            <strong>DUM </strong>
        {%- else -%}
            ba
        {%- endif -%}
    {%- endfor -%}
    <br>
    ({{ meter.pattern|length }} beats)
    </p>
{% else %}
    <h1>Add a New Meter</h1>
    <br>
{% endif %}
{% if form is not none %}
    {{ wtf.quick_form(form) }}
    <br>
{% endif %}
{% if delete_form is not none %}
    {{ wtf.quick_form(delete_form) }}
{% endif %}
{% if poems != [] %}
<b>Used in these Poems:</b>
    {% for poem in poems %}
        <li><a href="{{ url_for('poetry.poem', keyword=poem.keyword) }}">{{poem.title}}</a></li>
    {% endfor %}
{% endif %}
{% endblock page_content %}

run/templates/poetry/meter_list.html
{% extends "base.html" %}

{% block title %}
    Meter List - Metroscope
{% endblock title %}

{% block page_content %}
{% if meters == [] %}
    <h1>Sorry, no meters in the database!</h1>
    <p>Click <a href="{{ url_for('poetry.add_samples') }}">here</a> to load some samples!</p>
{% else %}
    <h1>Available Meters:</h1>
    {% for meter in meters %}
        <li><a href="{{ url_for('poetry.meter', keyword=meter.id) }}">{{meter.name}}</a></li>
    {% endfor %}
{% endif %}
<br>
{% if current_user.can(Permission.ADD_METER) %}
<a class="btn btn-default" href={{ url_for('poetry.meter', keyword='new') }} role="button">Add New Meter</a>
{% endif %}
{% endblock page_content %}

run/templates/poetry/poem.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %}
{{ super() }}
<style>
    .match {color: black;}
    .mismatch {color: red;}
    .stressed {font-weight: bold;}
    .unstressed {}
    .missing {font-size: 80%;}
    .verse-number {
        text-align: right;
        padding-right: 5;
        padding-left: 0;
    }
    .verse {
        padding-right: 0;
        padding-left: 0;
    }
    .rhyme {
        text-align: left;
        padding-right: 0;
        padding-left: 5;
    }
    .stanza-separator {
        text-align: center;
    }
</style>
{% endblock %}


{% block title %}
{{ title }} - Metroscope
{% endblock title %}

{% block page_content %}
<a href="{{ url_for('poetry.poem_list') }}">
    <span class="glyphicon glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    Available Poems
</a>
<div class='container'>
    <div class="row">
        <div class="verse col-xs-offset-1 col-xs-10 col-sm-6 col-md-5 col-lg-4">
            <h1>{{ title }}</h1>
            <h3 style="text-align:right">
                by <a href={{ url_for('poetry.poet', keyword=poet.id) }}>
                    {{ poet.name }}
                </a>
            </h3>
            <br>
            <p>Scanned in <a href={{ url_for('poetry.meter', keyword=meter.id) }}>{{ meter.name }}</a></p>
        </div>
    </div>
    <form class="form-horizontal" method="POST" role="form" action="">
        <div class='form-group'>
            <div class="verse col-xs-offset-1 col-xs-10 col-sm-6 col-md-5 col-lg-4">
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.pattern) }}
                {% if form.set_as_default is defined %}
                    {{ wtf.form_field(form.set_as_default) }}
                    <br>
                {% endif %}
                {{ wtf.form_field(form.submit, class="btn btn-primary btn-block") }}
            </div>
        </div>
    </form>
{% for lines, rhymes in stanzas %}
{% set stanza_loop = loop %}
    {% for line in lines %}
    <div class="row">
        <div class="verse-number col-xs-1">
            <small class="text-muted">
        {%- if stanza_loop.length == 1 %}
            {{ loop.index }}
        {% else %}
            {{ stanza_loop.index }}.{{ loop.index }}
        {% endif %}
            </small>
        </div>
        <div class="verse col-xs-10 col-sm-6 col-md-5 col-lg-4">
    {% for word in line.words %}
        {% for syllable in word.syllables -%}
            {%- if syllable.match -%}
                {%- set match_class = 'match' -%}
            {%- else -%}
                {%- set match_class = 'mismatch' -%}
            {%- endif -%}
            {%- if syllable.stress is none -%}
                {%- set stress_class = 'missing' -%}
            {%- elif syllable.stress -%}
                {%- set stress_class = 'stressed' -%}
            {%- else -%}
                {%- set stress_class = 'unstressed' -%}
            {%- endif -%}
            <span class='{{ match_class }} {{ stress_class }}'>{{syllable.text}}</span>
        {%- endfor %}
    {% endfor %}
        {% if loop.last and not stanza_loop.last %}
            <div class="stanza-separator text-muted">
                <br>
            </div>
        {% endif %}
        </div>
        {% set rp = line.rhyming_part|string %}
        <div class="rhyme col-xs-1">
            <small class="text-muted" data-toggle='tooltip' title='{{ rp }}'>
                {{ rhymes[rp] }}
            </small>
        </div>
    </div>
    {% endfor %}
{% endfor %}
</div>
{% endblock page_content %}

{% block scripts %}
{{super()}}
<script>
    $(document).ready(function(){
      $("[data-toggle='tooltip']").tooltip();
    });
</script>
{% endblock scripts %}

run/templates/poetry/poem_list.html
{% extends "base.html" %}

{% block title %}
    Poem List - Metroscope
{% endblock title %}

{% block page_content %}
{% if poems == [] %}
    <h1>Sorry, no poems in the database!</h1>
    <p>Click <a href="{{ url_for('poetry.add_samples') }}">here</a> to load some samples!</p>
{% else %}
    <h1>Available Poems:</h1>
    {% for poem in poems %}
        <li><a href="{{ url_for('poetry.poem', keyword=poem.keyword) }}">{{poem.title}}</a></li>
    {% endfor %}
{% endif %}
{% endblock page_content %}

run/templates/poetry/poet.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
{{ title }} - Metroscope
{% endblock title %}

{% block page_content %}
<a href="{{ url_for('poetry.poet_list') }}">
    <span class="glyphicon glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    Available Poets
</a>
{% if poet is not none %}
    <h1>{{ poet.name }}</h1>
    <br>
{% else %}
    <h1>Add a New Poet</h1>
    <br>
{% endif %}
{% if form is not none %}
    {{ wtf.quick_form(form) }}
    <br>
{% endif %}
{% if delete_form is not none %}
    {{ wtf.quick_form(delete_form) }}
{% endif %}
{% if poems != [] %}
<b>Used in these Poems:</b>
    {% for poem in poems %}
        <li><a href="{{ url_for('poetry.poem', keyword=poem.keyword) }}">{{poem.title}}</a></li>
    {% endfor %}
{% endif %}
{% endblock page_content %}

run/templates/poetry/poet_list.html
{% extends "base.html" %}

{% block title %}
    Poet List - Metroscope
{% endblock title %}

{% block page_content %}
{% if poets == [] %}
    <h1>Sorry, no poets in the database!</h1>
    <p>Click <a href="{{ url_for('poetry.add_samples') }}">here</a> to load some samples!</p>
{% else %}
    <h1>Available Poets:</h1>
    {% for poet in poets %}
        <li><a href="{{ url_for('poetry.poet', keyword=poet.id) }}">{{poet.name}}</a></li>
    {% endfor %}
{% endif %}
<br>
{% if current_user.can(Permission.ADD_POEM) %}
<a class="btn btn-default" href={{ url_for('poetry.poet', keyword='new') }} role="button">Add New Poet</a>
{% endif %}
{% endblock page_content %}